
title: Karlin Smith's Digital Portfolio
email: 
description: >- # this means to ignore newlines until "baseurl:"
  This is my senior year Honors Engineering portfolio! Here you will find the projects that I have woked on throughout
  my senior year as well as some of my reflections on the process.
github_username: KarlinSmith08
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Karlin Smith"
  avatar : "/assets/images/KarlinBioPhoto.JPG"
  bio    : "Senior at Charlotte Latin School. I will be attening Bucknell University in the fall of 2026 to study Biomedical Engineering."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://karlinsmith08.github.io/KarlinSmithPortfolio/"
    - label: "Personal GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/KarlinSmith08/KarlinSmithPortfolio"
    - label: "GitHub for work with the Pearl"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/26wickhm/pearl"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/karlin-grace-smith"

 

footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://karlinsmith08.github.io/KarlinSmithPortfolio/"
    - label: "Personal GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/KarlinSmith08/KarlinSmithPortfolio"
    - label: "GitHub for work with the Pearl"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/26wickhm/pearl"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/karlin-grace-smith"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
